#!/bin/bash

echo "=========================================="
echo "  GOOGLE CLIENT ID SETUP HELPER"
echo "=========================================="
echo ""
echo "For your Codedly app using Supabase OAuth:"
echo ""
echo "🌐 STEP 1: Get SHA-1 for Android (if needed)"
echo "----------------------------------------"
echo "Run this command to build and get SHA-1:"
echo ""
echo "  cd android && ./gradlew signingReport"
echo ""
echo "Look for 'SHA1' under 'Variant: debug'"
echo ""
echo "=========================================="
echo ""
echo "🔑 STEP 2: Create OAuth Credentials"
echo "----------------------------------------"
echo "1. Go to: https://console.cloud.google.com/apis/credentials"
echo ""
echo "2. Click: '+ CREATE CREDENTIALS' → 'OAuth client ID'"
echo ""
echo "3. Create THREE different client IDs:"
echo ""
echo "   📱 WEB CLIENT (REQUIRED for Supabase):"
echo "   ├─ Application type: Web application"
echo "   ├─ Name: Codedly Web"
echo "   ├─ Authorized JavaScript origins:"
echo "   │  └─ https://pzezxtsyujkwhphghyyt.supabase.co"
echo "   └─ Authorized redirect URIs:"
echo "      └─ https://pzezxtsyujkwhphghyyt.supabase.co/auth/v1/callback"
echo ""
echo "   📱 ANDROID CLIENT (Optional):"
echo "   ├─ Application type: Android"
echo "   ├─ Name: Codedly Android"
echo "   ├─ Package name: com.example.codedly"
echo "   └─ SHA-1: [Get from gradlew signingReport]"
echo ""
echo "   📱 iOS CLIENT (Optional):"
echo "   ├─ Application type: iOS"
echo "   ├─ Name: Codedly iOS"
echo "   └─ Bundle ID: com.example.codedly"
echo ""
echo "=========================================="
echo ""
echo "⚙️  STEP 3: Configure Supabase"
echo "----------------------------------------"
echo "1. Go to: https://app.supabase.com/project/pzezxtsyujkwhphghyyt/auth/providers"
echo ""
echo "2. Find 'Google' provider"
echo ""
echo "3. Enable it and paste:"
echo "   ├─ Client ID: [From WEB CLIENT]"
echo "   └─ Client Secret: [From WEB CLIENT]"
echo ""
echo "4. Click SAVE"
echo ""
echo "=========================================="
echo ""
echo "📝 IMPORTANT NOTES:"
echo "----------------------------------------"
echo "❌ You DON'T need GOOGLE_CLIENT_ID in .env file"
echo "   (Supabase handles OAuth on their server)"
echo ""
echo "✅ Only configure in Supabase Dashboard"
echo ""
echo "✅ Web Client ID + Secret go to Supabase"
echo ""
echo "✅ Android/iOS clients are optional"
echo "   (only needed for native Google Sign-In SDK)"
echo ""
echo "=========================================="
echo ""
echo "🧪 STEP 4: Test"
echo "----------------------------------------"
echo "Run: flutter run"
echo "Click: 'Sign in with Google' button"
echo "Select: Your Google account"
echo "Verify: Redirects back to app and logs in"
echo ""
echo "=========================================="
